- name: Set hostname to persist and set hostname
  hosts: "all"
  become: yes
  gather_facts: True
  tasks:
    - name: set cloud config
      template:
        src: /home/mike/ansible/templates/cloud.cfg
        dest: /etc/cloud/cloud.cfg
    
    - name: set hostname
      hostname:
        name: "{{ hostname }}"

    - name: make .ssh directory
      file:
        path: ~/.ssh
        state: directory

    - name: copy authorized_keys
      template:
        src: /home/mike/ansible/templates/authorized_keys
        dest: ~/.ssh/authorized_keys