---

- hosts: all
  become: true
  tasks:

  - name: add ssh keys for managing from laptop
    authorized_key:
      user: mike
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN/jrJ+zFanvfulB/yVDL9DUDZsnlQIbcu8yQTg1I2r1 Fizz

  - name: add ssh keys for managing from desktop
    authorized_key:
      user: mike
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILJlxB2XT/CFwdcMoc8j/dOoEWCdBi03RVBZeGnJSpEu Tryndamere

  - name: add ssh keys for managing from CodeServer
    authorized_key:
      user: mike
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGHneKprg5RqqQDs4gbeGqnvhF014qfLZGlw1v0aOPCV CodeServer
